### ISSUE TITLE
博文可读性太差

### ISSUE THREAD

**Issue by FantasticLBP** [RPGLiker/StudyBlog#1]
下载项目链接

Add objectivec/*.h, objectivec/google/protobuf/*.pbobjc.h, and objectivec/GPBProtocolBuffers.m to your project.
为了方便起见,我已经把这个整理好了,直接拖到项目里中就可以使用.链接,注意需要把这几个实现文件的内存管理变更为MRC,之后把你之前根据.proto生成的代码文件拷贝进去就可以.

-----------

很简单的东西被你这样描述下来步骤繁琐，文件夹还自己将 .h 和 .m 分开整理 😂

**Comment by harofan** [comment]
这描述是google自己的描述...至于分开我是打算给自己项目做成静态库直接用的, 这就直接把之前的拖了过来
